#!/usr/bin/env bash

#: exec_target = cli

## Initialize/reinstall site
##
## Usage: fin build-theme

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# PROJECT_ROOT, DOCROOT are set as env variables in
SITE_SUB_PATH='site'
SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITE_CODE_PATH="${PROJECT_ROOT}/${SITE_SUB_PATH}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"
CUSTOM_THEME_PATH="${PROJECT_ROOT}/${SITE_SUB_PATH}/web/themes/custom"


#-------------------------- END: Settings --------------------------------

#-------------------------- Functions --------------------------------

if [[ "${1}" == "" ]]; then
  echo "Need to specify your custom theme name.  We are assuming it lives in ${CUSTOM_THEME_PATH}"
  exit
else
  cd "${CUSTOM_THEME_PATH}/${1}"
  npm install
  gulp
fi