#!/usr/bin/env bash

## Initialize stack and site (full reset)
##
## Usage: fin init

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

NODE_VERSION=14.17.1

# PROJECT_ROOT and DOCROOT are set as env variables in cli
SITE_SUB_PATH="site"
SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITE_CODE_PATH="${PROJECT_ROOT}/${SITE_SUB_PATH}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[1;97;42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

#-------------------------- Execution --------------------------------
echo ${SITE_SUB_PATH} exit
# Stack initialization
echo -e "${green_bg} Step 1 ${NC}${green} Initializing stack...${NC}"
fin project reset -f


echo -e "${green_bg} Step 1 ${NC}${green} Initializing NodeJs, Gulp and Python2 ${NC}"
fin exec nvm install  ${NODE_VERSION}
fin exec nvm alias default  ${NODE_VERSION}
fin exec npm install gulp --global
fin exec npm link gulp --force
fin exec sudo apt update
fin exec sudo apt install -y python2

# Site initialization
# This runs inside cli using http://docs.docksal.io/en/v1.4.0/fin/custom-commands/#executing-commands-inside-cli
if [[ "${1}" == "drupal-org-dev" ]];
then
  echo -e "${green_bg} Step 2 ${NC}${green} Running composer install for Drupal.org Development...${NC}"
  fin composer-install drupal-org-dev
else
  echo -e "${green_bg} Step 2 ${NC}${green} Getting latest Provus and running composer install...${NC}"
  fin composer-install
fi
echo -e "${green_bg} Step 3 ${NC}${green} Initializing site...${NC}"
fin init-site

echo -e "${green_bg} DONE! ${NC}${green} Completed all initialization steps.${NC}"

#-------------------------- END: Execution --------------------------------
